# These are supported funding model platforms

github: [JoshiMitesh]
patreon:
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee: miteshjoshd
thanks_dev:
custom:

